# Interpulation
This notebook will concetrate on the Lagrange interpulation

### Intro
Interpulation theorem is the heart of classic numeric analisys.


#### The main idea.
$$
\text{ Let }y=f(x)
\text{ with known valus in set of points: }\\
\text{ in range: }[a,b] \text{ so: }\\
a \le x_0 \lt x_1 \lt \cdots \lt x_n \le b
$$


Meaning, given the next table of values:

In [137]:
import numpy as np
N = 10
values_table = np.array([["x{}".format(index),"y{}".format(index)]for index in range(N+1)]  )
print("Valus table: \n")
print(values_table)

Valus table: 

[['x0' 'y0']
 ['x1' 'y1']
 ['x2' 'y2']
 ['x3' 'y3']
 ['x4' 'y4']
 ['x5' 'y5']
 ['x6' 'y6']
 ['x7' 'y7']
 ['x8' 'y8']
 ['x9' 'y9']
 ['x10' 'y10']]


$\text{And: }
y_k=f(x_k)
$

#### Iterpulation purpose: 
to approximate $f(x)$ in section $[a,b]$
by <b>polynom</b> $L(x)$ that coalesce with $f(x)$ on the given points (values table).

Meaning a polynom that uphold:
$$
L(x_k)=y_k ; \quad \forall k=0,1,\ldots,n
$$

#### For point that are not given in the table:
The Interpulation pulynom **approximate** the function value
$$
L(x)\cong f(x) ; \quad \forall x\ne x_k
$$

In addition, One need to find Error bound, between the approximated value of the function to the REAL value, at every point in the section that is NOT in the table.

In [138]:
import chart_studio.plotly  as py
import plotly.graph_objs as go

import numpy as np
import pandas as pd
import scipy

points = np.array([(1, 1), (2, 4), (3, 1), (9, 3)])
print("Given table: ")
print(points)

x = points[:,0]
y = points[:,1]


trace1 = go.Scatter(
    x=x,
    y=y,
    mode='markers',
    name='Data',
    marker=dict(
        size=12
    )
)

layout = go.Layout(
    title='Given pionts from table.'
)

data = [trace1, ]
fig = go.Figure(data=data, layout=layout)

fig
#py.iplot(fig, filename='interpolation-and-extrapolation')

Given table: 
[[1 1]
 [2 4]
 [3 1]
 [9 3]]


In [139]:
z = np.polyfit(x, y, 3)
f = np.poly1d(z)
print("\nThe interpulated polinum f(x):\n")
print("{}".format(f))

x_new = np.linspace(0, 10, 50)
y_new = f(x_new)


trace2 = go.Scatter(
    x=x_new,
    y=y_new,
    mode='lines',
    name='Fit'
)

annotation = go.layout.Annotation(
    x=6,
    y=-4.5,
    text="{'$0.43X^3 - 5.607X^2 + 16.78X - 10.61$'}",
    showarrow=False
)

layout = go.Layout(
    title='Polynomial Fit in Python',
    annotations=[annotation]
)

data = [trace1, trace2]
fig = go.Figure(data=data, layout=layout)

fig


The interpulated polinum f(x):

        3         2
0.4345 x - 5.607 x + 16.78 x - 10.61


### Prooving: existence of the lagrange interpulation polynom:
In lecture 6, in the moodle.

In this proof, instead of using the standart basis 
$ \{ 1,x,x^2,\ldots,x^n \}$, to the polynomial space $R_n[x]$, we built a SPECIFIC basis that are relevant to the **interpulation points** it looks like this:

$$
l_0(x) = \frac{(x-x_1)(x-x_2)\cdots (x-x_n)}{(x_0 - x_1)(x_0 - x_2)\cdots (x_0- x_{n})}\\
l_1(x) = \frac{(x-x_0)(x-x_2)\cdots (x-x_n)}{(x_1 - x_0)(x_1 - x_2)\cdots (x_1- x_{n})}\\
\vdots\\
l_k(x) = \frac{(x-x_0)(x-x_1)\cdots (x-x_{k-1})(x-x_{k+1})\cdots (x-x_n)}{(x_k - x_0)(x_k - x_1)\cdots (x_k-x_{k-1})(x_k-x_{k+1})\cdots (x_k- x_{n})}\\
\vdots\\
l_n(x) = \frac{(x-x_0)(x-x_1)\cdots (x-x_{n-1})}{(x_n - x_0)(x_n - x_1)\cdots (x_n- x_{n-1})}
$$

We will not continue the proof from lecture 6, instead will jump to the example:

### Example for lagrange representation of the Interpulation polynom:

In [140]:
points = np.array([(1, 1), (4, 2), (9, 3)])
print("Given table: ")
print(points)

x = points[:,0]
y = points[:,1]


trace1 = go.Scatter(
    x=x,
    y=y,
    mode='markers',
    name='Data',
    marker=dict(
        size=12
    )
)

given_function = '$y=\sqrt{x}$'

# Insert annotation to the graph
annotation0 = go.layout.Annotation(
    x=0,
    y=3.5,
    text="And given the function:".format(given_function),
    showarrow=False
)
annotation1 = go.layout.Annotation(
    x=3,
    y=3.5,
    text="{}".format(given_function),
    showarrow=False
)

layout = go.Layout(
    title='Given pionts from table.',
    annotations=[annotation0,annotation1]
)

data = [trace1, ]
fig = go.Figure(data=data, layout=layout)

fig

Given table: 
[[1 1]
 [4 2]
 [9 3]]


Given the function $y=\sqrt{x}$
Will build an Interpulation polinom from degree $\le 2$:

$$
L_2(x) = y_0\cdot l_0(x)+y_1\cdot l_1(x)+y_2\cdot l_2(x)
$$

Let us calculate the lagrange elementric polynoms, according to given table:

$$
l_0(x) = \frac{(x-4)(x-9)}{(1-4)(1-9)} = \frac{1}{24}(x-4)(x-9)
$$

In [141]:
print("And in python.\n")
print("Well call the L(desired_degree,X,given_table):\n")
def L(degree,x_input,given_table,debug=False):
    L_degree_retult = 0
    x_input = x_input
    interpulation_polynom_degree = 0
    
    x = points[:,0]
    y = points[:,1]
    for y_point in y:
        
        if interpulation_polynom_degree <= degree:
            numerator = []
#            print("*"*10)
#            print("Calculating l_{}:".format(interpulation_polynom_degree))
#            print("")
            for index,number in enumerate(x):
                if index is not interpulation_polynom_degree:
#                    print("({}-{})".format(x_input,number),end = '')
                    numerator.append(x_input-number)
            
#            print("")
#            print("-"*4*len(x)) 

            
            
            denominator = [x[interpulation_polynom_degree] - number for number in x[x != x[interpulation_polynom_degree]]]
#            print("denominator: \n{}\n".format(denominator))
            
            prod_numerator = np.prod(numerator)
            prod_denominator = np.prod(denominator)
#            print("final denominator: \n{}\n".format(denominator))
            
            interpulation_polynom_degree = interpulation_polynom_degree + 1
#            print("y_point: {}".format(y_point))
            
            L_degree_retult = L_degree_retult + y_point*(prod_numerator/prod_denominator)
#            print("L_degree_retult: {}".format(L_degree_retult))

    if debug is True:
        print("*"*10)
        print("Calculating Interpulation polynom...")
        for degree in range(interpulation_polynom_degree):
            print(degree)
            print(numerator)
            #print("({}-{})".format(x_input,numerator[degree]),end = '')
            print(denominator)
        
    return L_degree_retult

And in python.

Well call the L(desired_degree,X,given_table):



In [142]:
print("Test function according to given points:")

result = []
result = [(given_x,L(2,given_x,points)) for given_x in points[:,0]]
result = np.array(result,dtype=np.int32)
print("This is the result from our tests: \n(x.y)\n{}".format(result)) 

Test function according to given points:
This is the result from our tests: 
(x.y)
[[1 1]
 [4 2]
 [9 3]]


Now that we have calculated L_2 interpulation pulynom for all given points from table, lets test measure our error:

In [143]:
points = np.array([(1, 1), (4, 2), (9, 3)])
print("The Given table: ")
print(points)

x = points[:,0]
y = points[:,1]


trace1 = go.Scatter(
    x=x,
    y=y,
    mode='markers',
    name='Data',
    marker=dict(
        size=12,
        color=[5,5,5]
    )
)

xres=result[:,0]
yres=result[:,1]
trace2 = go.Scatter(
    x=xres,
    y=yres,
    mode='markers',
    name='Interpulated',
    marker=dict(
        size=10,
        
    )
)

layout = go.Layout(
    title='Given pionts from table VS interpulated using L_2 interpulation pylinom.',
    annotations=[]
)

data = [trace1,trace2 ]
fig = go.Figure(data=data, layout=layout)

fig

The Given table: 
[[1 1]
 [4 2]
 [9 3]]


#### Note:
We can see that the interpulated points from the given table are the same as the given points them selfs. But what if we take some other point within $[1,9]$?

We can see that using this interpulation polynom, interpulating some other points within given range can approximate to the real value. for example:

Lets interpulate $\sqrt{3}$ using our interpulation polynum from 2 degree:


In [147]:
print("We and approximation of : {}".format(L(2,3,points)))

We and approximation of : 1.7000000000000002


While the real value of $\sqrt{3}=1.73205$

We can see that even if the point is within the range of given points, there's still an Error.



In [ ]:
# Data manipulation
import pandas as pd
import numpy as np

# Options for pandas
pd.options.display.max_columns = 50
pd.options.display.max_rows = 30

# Display all cell outputs
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

from IPython import get_ipython
ipython = get_ipython()

# autoreload extension
if 'autoreload' not in ipython.extension_manager.loaded:
    %load_ext autoreload

%autoreload 2

# Visualizations
import plotly.plotly as py
import plotly.graph_objs as go
from plotly.offline import iplot, init_notebook_mode
init_notebook_mode(connected=True)

import cufflinks as cf
cf.go_offline(connected=True)
cf.set_config_file(theme='white')

# Analysis/Modeling
Do work here

# Results
Show graphs and stats here

# Conclusions and Next Steps
Summarize findings here