# The gauss method
An algebra reminder

1. matrice - intruduction to solution linear equations system.
2. Liner equations system - into.
3. Gauss method

In [1]:
import numpy as np
a = np.matrix([[1, 2], [3, 4]])
print("The matrix a:")
print(a)

The matrix a:
[[1 2]
 [3 4]]


### 1. matrice - intruduction to solution linear equations system.

<b>Some elementric actions on matrice rows.</b>
<br>
Let $R_i$ will be the i'th row of the matrice.
<br>
<br>
<b>Definition:</b>
<br>
the actions below are called <b>elementery actions</b> in the matrice row:
1. $ R_i \leftrightarrow R_j$ replacing the i'th row with j'th.

In [2]:
print("\nReplacing the i'th row with j'th:")
b = np.array(a, copy=True)
b[0] = b[1]

print(b)


Replacing the i'th row with j'th:
[[3 4]
 [3 4]]


2. $ R_i \rightarrow c \cdot R_j, c \neq 0$ multiply i'th row in constant "scalar".


In [3]:
print("\nmultiply i'th row in constant 'scalar':")
scalar = 4
c = np.array(a, copy=True)

c[0] = 4*c[0]

print(c)


multiply i'th row in constant 'scalar':
[[4 8]
 [3 4]]


3. $R_i \rightarrow R_i+ c\cdot R_j, i \neq j$ Add $c$ times j'th row to i'th row.

# Analysis/Modeling
Do work here

# Results
Show graphs and stats here

# Conclusions and Next Steps
Summarize findings here